dir = "@bigmod";
name = "Big Mod";
picture = "bigmod\addons\not\nice\path\with\backslashes\picture.paa";
actionName = "$STR_MOD_LAUNCHER_ACTION";
action = "https://bigmod.somewhere";
description = "Bugtracker: https://bigmod.somewhere/issues<br/>Documentation: https://bigmod.somewhere/wiki";
hideName = 1;
hidePicture = 0;
logo = "bigmod\addons\not\nice\path\with\backslashes\logo.paa";
logoOver = "bigmod\addons\not\nice\path\with\backslashes\logo.paa";
tooltip = "Big Mod";
tooltipOwned = "Big Mod Owned";
overview = "Big Mod is very Big.";
author = "Big Modders";
overviewPicture = "bigmod\addons\not\nice\path\with\backslashes\logo.paa";
overviewText = "Big Mod for Arma 3";
overviewFootnote = "<br /><br /><t color='#aa00aa'>Some random bla bla with HTML tags.<br />This will be <t /><t color='#ffaa00'>annoying<t /> to parse";
version = "1.0a";
